name: Static Analysis
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    name: phpstan
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v2
    - uses: dingo-d/phpstan-wp-action@v1
      with:
        level: 8
